### ISSUE TITLE
Add NIDS from the wiki and the pastebin file to db.yml

### ISSUE THREAD

**Issue by devnoname120** [vitasdk/vita-headers#108]

**Comment by yifanlu** [comment]
What's the status on this?

**Comment by devnoname120** [comment]
No advancement on my side, I have made some tool which could do that with few modifications.
https://github.com/devnoname120/vitasdk-db-tools/blob/master/dbtools.py

**Comment by motoharu-gosuto** [comment]
Here is another solution for wiki:
https://github.com/motoharu-gosuto/HenkakuWikiAgg
Created some time ago so probably it should be tested properly. Maybe fixed/improved.

**Comment by devnoname120** [comment]
Closed by https://github.com/vitasdk/vita-headers/pull/390.
