### ISSUE TITLE
Add names to anonymous enumerations

### ISSUE THREAD

**Issue by devnoname120** [vitasdk/vita-headers#110]
Example in display.h:

```C
 enum {
     SCE_DISPLAY_SETBUF_IMMEDIATE = 0,
     SCE_DISPLAY_SETBUF_NEXTFRAME = 1
 };
```

should be replaced with

```C
typedef enum SceDisplaySetBufSync {
     SCE_DISPLAY_SETBUF_IMMEDIATE = 0,
     SCE_DISPLAY_SETBUF_NEXTFRAME = 1
 } SceDisplaySetBufSync;
```

It can then be referenced in the documentation as `::SceDisplaySetBufSync`.

**Comment by d3m3vilurr** [comment]
all enum and defined type start upper case. so should be `SceDisplaySetBufSync`

**Comment by devnoname120** [comment]
Thanks, I modified the description accordingly.

**Comment by Rinnegatamante** [comment]
Can be closed i suppose.
