### ISSUE TITLE
Please add scePower NIDs

### ISSUE THREAD

**Issue by Yoti** [vitasdk/vita-headers#118]
`int scePowerRequestColdReset(void);`
`int scePowerRequestStandby(void);`
`int scePowerRequestSuspend(void);`
https://forums.vitasdk.org/viewtopic.php?f=4&t=14

**Comment by devnoname120** [comment]
They are already in the NID database (https://github.com/vitasdk/vita-headers/blob/master/db.yml).

Feel free to add them to [`power.h`](https://github.com/vitasdk/vita-headers/blob/master/include/psp2/power.h) and open a pull request.
