### ISSUE TITLE
Does scePowerSetArmClockFrequency function works?

### ISSUE THREAD

**Issue by ljkgpxs** [vitasdk/vita-headers#13]
I have found scePowerSetArmClockFrequency in libScePower_stub.a, it looks like a function to set cpu clock, and other functions about bus clock, gpu clock. But I dont find those APIs in vita-headers.
Do they work on psvita? Why not add those APIs to vita-headers?

**Comment by yifanlu** [comment]
yeah. I don't think people have gotten around to adding them yet. feel free to do so and send a pull request

**Comment by ljkgpxs** [comment]
Thanks for your reply, I have test it by adding them to source code!
