### ISSUE TITLE
libSceSsl_stub missing .h file

### ISSUE THREAD

**Issue by InvalidExcepti0n** [vitasdk/vita-headers#15]
working with HTTP had some issues, so started looking into it...
I found out SSL need to be initialised  (and I found lib but no .h file)
when I include .h with this 2 functions it worked
Reference: http://www.smartpsp.net/doxygen-doc-en/html/pspssl_8h.html

int sceSslInit(int poolSize);
int sceSslTerm(void);

as I opened lib with hex there is lot more functions but I needed only this ones
so if someone can look into it and make proper .h file

**Comment by xyzz** [comment]
Fixed by #21
