### ISSUE TITLE
sqlite3_temp_directory erroneously reported as function

### ISSUE THREAD

**Issue by Rinnegatamante** [vitasdk/vita-headers#16]
In db.json, sqlite3_temp_directory is exported as a function ( https://github.com/vitasdk/vita-headers/blob/master/db.json#L4116 ) even if it's in reality a variable ( https://www.sqlite.org/c3ref/temp_directory.html ) causing any attempt to access to such variable to end up with a system crash and a coredump.

**Comment by devnoname120** [comment]
Does #82 allow you to set `sqlite3_temp_directory`?

**Comment by Rinnegatamante** [comment]
iirc when i got stuck with this error, i had already tried to move it to the variables in the json database but it was already crashing. However i can give it a try again.

**Comment by xyzz** [comment]
@Rinnegatamante any progress with this?

**Comment by Rinnegatamante** [comment]
Crashes like it did with my old tests.

**Comment by devnoname120** [comment]
@Rinnegatamante Could you post your example? I would like to try to figure what's wrong.

**Comment by Rinnegatamante** [comment]
I just swapped AntiBlacklist code from using sqlite to SceSqlite for my test. Anyway it crashes at application startup so i suppose it can be reproduced with a really simple example (what you have to do to perform the crash is just to try to assign something to such variable).

**Comment by devnoname120** [comment]
I wonder if there is not some kind of restriction on the location from where the database can be loaded.

**Comment by Rinnegatamante** [comment]
Made some progress with this.
I managed to access databases with read privileges correctly using SceSqlite.
I'm 90% sure writing doesn't work cause sqlite3_temp_directory can't be set without a crash.
Using taiInjectData to write on it should solve the problem (i think).
According to sqlite3 manual, sqlite3_temp_directory must point to a string allocated using sqlite3_mprintf.

"Testcase" used: https://pastebin.com/L9msTsMJ (It's a modified version of AntiBlacklist.)

**Comment by devnoname120** [comment]
> sqlite3_temp_directory can't be set without a crash.

Did you move `sqlite3_temp_directory` to the variables section and recompiled the stub?

**Comment by Rinnegatamante** [comment]
I had tried this when we used to have a json db. I can try with the new one but i don't think it will change something.
