### ISSUE TITLE
Some SceCtrlButtons seems to not be interceptable

### ISSUE THREAD

**Issue by Rinnegatamante** [vitasdk/vita-headers#209]
SCE_CTRL_HEADPHONE , SCE_CTRL_VOLUP, SCE_CTRL_VOLDOWN, SCE_CTRL_POWER seems to not be interceptable by any usermode function. Not tested in kernel mode but it can be deleted from the psp2 part of the header files i assume.
https://github.com/vitasdk/vita-headers/blob/master/include/psp2/ctrl.h#L43

Testcase used:
https://pastebin.com/gKdFfP7J

**Comment by TheOfficialFloW** [comment]
It should be with shell permissions.

**Comment by devnoname120** [comment]
In case people willing to use those find this issue, shell permissions can be added by adding the following to your `CMakeLists.txt`:
```cmake
set(VITA_MAKE_FSELF_FLAGS "${VITA_MAKE_FSELF_FLAGS} -a 0x2800000000000001")
```
