### ISSUE TITLE
Update Doxygen to 1.8.14

### ISSUE THREAD

**Issue by devnoname120** [vitasdk/vita-headers#327]
I've tried on Windows and it seems broken, it will need to be fixed prior to updating it.

![image](https://user-images.githubusercontent.com/2824100/41203631-4ec04f5c-6cda-11e8-8334-484f1a52e499.png)

**Comment by d3m3vilurr** [comment]
recently kaist mirror has the problem over the 6hours.
i'll change the binary addr to official one & bump up version to 1.8.16

**Comment by devnoname120** [comment]
Please make sure that the issues I've mentioned in this issue are fixed prior to bumping the version.

**Comment by devnoname120** [comment]
Note that I've recently changed the doxygen link to a mirror: https://github.com/vitasdk/vita-headers/pull/422

**Comment by d3m3vilurr** [comment]
omg.... do you really think making `artifacts` is good idea?

**Comment by yne** [comment]
@d3m3vilurr It's always a good thing to keep your dependency on your side ;)

**Comment by d3m3vilurr** [comment]
@yne but also that is totally annoying thing.
if we had to always need to maintain the every dep tree, I try to find the package manager instead making the manual binary mirror.
