### ISSUE TITLE
VitaSDK documentation is currently unreadable on Firefox/Chrome

### ISSUE THREAD

**Issue by Luro02** [vitasdk/vita-headers#332]
At the moment I am unable to read the documentation because the menu is hiding the text :(
https://i.imgur.com/yt89gWT.png
https://i.imgur.com/yQobr5O.png

**Comment by d3m3vilurr** [comment]
![firefox_2018-07-05_16-37-22](https://user-images.githubusercontent.com/47262/42308826-bc135cb6-8071-11e8-9a60-4c22038513d5.png)

works well. please check your extensions
