### ISSUE TITLE
Two functions for one NID

### ISSUE THREAD

**Issue by scribam** [vitasdk/vita-headers#387]
Noticed twice:
- `pss_app_exit_liveboard` and `pss_errno_loc` have the same NID: `0x58ABAD62`
- `scePafResourceGetAttributeIdInt` and `scePafResourceGetAttributeIdIntLpb` have the same NID: `0xABFA169F`

**Comment by yne** [comment]
I think these are the only two inconsistencies, you can try with:
```
for dupNid in $(cat db.yml | grep -o 0x........ | sort | uniq -c | grep -v ' 1 ' | cut -b 9-); do
  echo $dupNid && grep $dupNid db.yml;
done;
```
I think it *may* be automatically detected as long as we respect the `sce`/`ksce` naming for functions that share the same NID

**Comment by CelesteBlue-dev** [comment]
@scribam Was this duplicate name fixed ?
