### ISSUE TITLE
Inconsistancy in the headers

### ISSUE THREAD

**Issue by SMOKE5** [vitasdk/vita-headers#4]
The more I get into developing things on Vita, the more I notice how inconsistent the headers are between each other. For example, the constants in ctrl.h are named such as this: PSP2_CTRL_MODE_ANALOG and meanwhile in touch.h, constants are named with a SCE prefix instead of PSP2: SCE_TOUCH_SAMPLING_STATE_START

IMO it should be more consistent across the various headers, but I don't see how that can be done without creating compile errors on pretty much every homebrew / library out there.

So, what ( if anything ) could be done about this?

**Comment by xyzz** [comment]
We can have both, for example, replace PSP2_ with SCE_ and have the old PSP2_* #define'd to the new SCE_ prefix.

Do we know what's the reason @173210 went with the PSP2_/SCE_ separation?

**Comment by 173210** [comment]
SCE_ and sce prefix are used for definitions which should be defined in SCE's SDK.
But, actually the inconsistency is confusing. We may add definitions with PSP2_ and psp2 prefix with macros, or simply remove SCE_ and sce prefix definitions.

**Comment by SMOKE5** [comment]
As discussed in #vitasdk, I removed the PSP2 prefix all together in the headers. It now uses the SCE prefix exclusively

**Comment by xyzz** [comment]
Fixed now, thanks
