### ISSUE TITLE
duplicate function definitions cause linking issue

### ISSUE THREAD

**Issue by soarqin** [vitasdk/vita-headers#400]
As imported from https://wiki.henkaku.xyz/vita/SceSysmem in commit https://github.com/vitasdk/vita-headers/commit/f9c34e287b630e6c0d8ae312540d7bbbfa314f51:
Both `sceKernelCreateUidObjForDriver `and `sceKernelCreateUidObjForKernel `are renamed to functions with same name: `ksceKernelCreateUidObj`
It makes new compiled taiHEN kernel plugin not working properly due to linking `ksceKernelCreateUidObj `to `sceKernelCreateUidObjForDriver `instead of `sceKernelCreateUidObjForKernel`

Although the temproary resolution is that put SceSysmemForKernel_stub before SceSysmemForDriver_stub in target_link_libraries, it is better to avoid duplicate function names in SDK libs.

**Comment by d3m3vilurr** [comment]
how about rename `sceKernelCreateUidObjForKernel` to `ksceKernelCreateUidObjWithOpt`
or `sceKernelCreateUidObjForDriver` to `ksceKernelCreateUidObjWithoutOpt`
(or just remove `sceKernelCreateUidObjForDriver`)
but actually we need reversed code.

**Comment by d3m3vilurr** [comment]
we need a rule for this problem also should make the linting to detect the dup name.
but I'm lazy man, just rename `sceKernelCreateUidObjForDriver` to `ksceKernelCreateUidObj2` in this time.
