### ISSUE TITLE
Need to separate headers for each library

### ISSUE THREAD

**Issue by Princess-of-Sleeping** [vitasdk/vita-headers#405]
For example, "psp2kern/kernel/sysmem.h" is written to link SceSysmemForDriver_stub, but ksceKernelRxMemcpyKernelToUserForPid or ksceKernelGetSysrootBuffer etc. throws an error as a function that is not defined even if SceSysmemForDriver_stub is linked.

So to avoid the error
sysmem_driver.h : SceSysmemForDriver
sysmem_kernel.h : SceSysmemForKernel
sysroot_driver.h : SceSysrootForDriver
sysroot_kernel.h : SceSysrootForKernel
Need to be like

**Comment by CelesteBlue-dev** [comment]
omg all these issues and workarounds coming just because someone refused to name functions ForKernel and ForDriver

**Comment by Princess-of-Sleeping** [comment]
Anyway, we propose to separate the header for each library

**Comment by CelesteBlue-dev** [comment]
Feasible but not optimal:
- SCE uses sysmem.h, not per library
- if you have 2 functions using same struct, where do you define the struct ? In a 3rd header ? That would make us alway need sysmem.h + sysmem_for_xxx.h
- to keep compatibility with current homebrews, it is better to keep using ONLY sysmem.h

**Comment by Princess-of-Sleeping** [comment]
If there are two functions with the same structure, they are defined in types.h.
If sysmem_for_xxx.h is not optimal, it is necessary to separate ForDriver and ForKernel functions with comments etc. in sysmem.h for easy understanding.

**Comment by DaveeFTW** [comment]
@noname120 is it possible to add the second lib to the header?

**Comment by devnoname120** [comment]
If your question is about doxygen then yes: https://github.com/vitasdk/vita-headers/blob/837b75ed4c6531860775805fb71ea279f39252eb/docs/Doxyfile#L243

**Comment by Princess-of-Sleeping** [comment]
From now on, this is how avoid problems.
https://github.com/vitasdk/vita-headers/commit/bc5965eafde08dca831e4720aabcb3e3374cbcdd#diff-2bd655329132139b217e744348ab8c43da998c5d8db036121dd6c2d5f0383c7cR6

Unless there is an innovative alternative, this issue will not resume.
Thanks.
