### ISSUE TITLE
SceAppMgr

### ISSUE THREAD

**Issue by BenMitnicK** [vitasdk/vita-headers#416]
when I use the old SceAppMgr library it's ok work fine but with the newest version I have this error:

undefined reference to `sceAppMgrLaunchAppByName2'

Maybe a fix ?

**Comment by Princess-of-Sleeping** [comment]
maybe SceDriverUser_stub

**Comment by BenMitnicK** [comment]
thank you that's it. there are many things that have been changed, where to go to see the changes of the library ? because I have another problem.

**undefined reference to `sceAppMgrUmount'**

he also has to change places how to know all that to avoid some issue
thanks in advance

**Comment by Princess-of-Sleeping** [comment]
look db.yml

**Comment by BenMitnicK** [comment]
yes I found the file, everythink is ok. THX very much :)

**Comment by d3m3vilurr** [comment]
sadly we partially revert #410 changes in #415 
so `sceAppMgrUmount` return to `SceAppMgr` from `SceDriverUser`
sorry about this :(

**Comment by BenMitnicK** [comment]
no worries, now i know or look :)
