### ISSUE TITLE
Functions with the same nid exist

### ISSUE THREAD

**Issue by Princess-of-Sleeping** [vitasdk/vita-headers#428]
SceKernelThreadmgr export
```
kernel
//174: ksceKernelGetMutexInfo 0x69b78a12 @OFF: 0xe819 VADDR: 0x8100e819

user
//393: SceThreadmgr_69B78A12 0x69b78a12 @OFF: 0x2d6fd VADDR: 0x8102d6fd
```

**Comment by CelesteBlue-dev** [comment]
same NID -> same short name i.e SceThreadmgr_69B78A12 = sceKernelGetMutexInfo
right ?

**Comment by Princess-of-Sleeping** [comment]
Yes, maybe

**Comment by d3m3vilurr** [comment]
interesting. we should split group to check kernel & user.

**Comment by d3m3vilurr** [comment]
@Princess-of-Sleeping I check the current linting chain. it allows conflict NID between kernel & user.
can you explain detail problem?

**Comment by Princess-of-Sleeping** [comment]
The problem is that the kernel export has the same nid

**Comment by Princess-of-Sleeping** [comment]
Discover another example
```
//19 : SceThreadmgrForKernel_1E82E5D0 0x1e82e5d0 @OFF: 0xe551 VADDR: 0x8100e551
//103: ksceKernelUnlockMutex 0x1e82e5d0 @OFF: 0xe551 VADDR: 0x8100e551
//347: SceThreadmgr_1E82E5D0 0x1e82e5d0 @OFF: 0x2d785 VADDR: 0x8102d785
```

**Comment by Princess-of-Sleeping** [comment]
Since these problems occur in different libraries, I decided that there was no problem and decided to close this issues.
Thanks.
