### ISSUE TITLE
socket sceNetSend looks not working properly

### ISSUE THREAD

**Issue by phonixivan** [vitasdk/vita-headers#429]
I create a server on vita and a client on pc, why I break the connect, the send function still works and not throw error？

**Comment by phonixivan** [comment]
how to judge  disconnection?

**Comment by yne** [comment]
IIRC `sceNetSend` return the amout of byte sent.

So I guess it will return < 0 in case of error.

**Comment by d3m3vilurr** [comment]
@yen's answer is right.

https://github.com/vitasdk/newlib/blob/3e45c76/newlib/libc/sys/vita/socket.c#L302-L324 here is our socket `send` implementation.
sceNetSend will return byte length and negative value is an error.

**Comment by phonixivan** [comment]
@yne 
It works! thank you!
