### ISSUE TITLE
Libraries of the module SceDriverUser are in wrong modules

### ISSUE THREAD

**Issue by cuevavirus** [vitasdk/vita-headers#439]
For example, the library SceAppMgrUser is in the module SceAppMgr but should be in the module SceDriverUser. Many other libraries of SceDriverUser are also in wrong modules.

**Comment by Rinnegatamante** [comment]
Backwards compatibility.
https://github.com/vitasdk/vita-headers/pull/410
https://github.com/vitasdk/vita-headers/commit/8fe91a2c81f90259acdfa850a797a549c99d5fe1

**Comment by d3m3vilurr** [comment]
#415 is an another case(and it contains SceAppMgr case)
we wouldn't fix it until resolving #331

**Comment by cuevavirus** [comment]
until resolviong #331 ok but why did you close this

several people have already brought up the same issue in the past and someone will repeat it in the future
