### ISSUE TITLE
Possible error in sceAppMgrLaunchAppByUri

### ISSUE THREAD

**Issue by Electric1447** [vitasdk/vita-headers#594]
https://github.com/vitasdk/vita-headers/blob/54c6bead61476b2d64f3565f02af01f298402e66/include/psp2/appmgr.h#L322-L332
Isn't 0xFFFFF also a valid flag?

**Comment by Electric1447** [comment]
Or does just this bit need to be one?
```
            here
               v
00000000 00000010 00000000 00000000
```

**Comment by Princess-of-Sleeping** [comment]
Many are just not REd or undocumented

**Comment by Electric1447** [comment]
should we document what we know?

**Comment by Princess-of-Sleeping** [comment]
If want you that, yes.

**Comment by KuromeSan** [comment]
i think 'flag' acturally determines if this can run "system" URI (encased in <> in SFO) or not .

https://github.com/vitasdk/vita-headers/issues/594#issuecomment-870549697 > if that bit is set then it can, if it is not then it cannot 

try using "mailto:" without that flag, it just works anyway ..

**Comment by Princess-of-Sleeping** [comment]
I RE found two things, but they weren't available in sceAppMgrLaunchAppByUri.

```C
#define SCE_APPMGR_IGNORED_NAME  0x100000
#define SCE_APPMGR_SOME_CALLBACK 0x840000
```

And RE this flags is very difficult.

Also, this issue is now closed due to no further progress. You can also reopen the issue for new further progress or whatever.
