### ISSUE TITLE
PS Vita Dev Wiki link on homepage dead

### ISSUE THREAD

**Issue by SoulRepo** [vitasdk/vita-headers#597]
Hey, it looks like the link on the homepage for the PS Vita dev wiki seems to be dead, as it moved to another domain without a redirect to the new one. Here's the new one: https://playstationdev.wiki/psvitadevwiki

**Comment by Rinnegatamante** [comment]
I don't see any reference to a wiki in this repository. Can you point out where are those references?

**Comment by SoulRepo** [comment]
Here: https://docs.vitasdk.org/

**Comment by Rinnegatamante** [comment]
Done with https://github.com/vitasdk/vita-headers/commit/bda10d0240414a3e190ac31dbbe108405714479a
