### ISSUE TITLE
Add a function to open quick menu without triggering the button

### ISSUE THREAD

**Issue by Hanzyusuf** [vitasdk/vita-headers#627]
I don't know if this is possible but would like to have a way to open the quick menu without pressing or triggering the PS button.

The problem is that a lot of people (including me) have a frozen power button, the PS home button does not work either when the power button is stuck, so there is no way to open the quick menu. 

I have also tried remapping the buttons in reVita, where the PS home button in combination hotkeys work too, but there is no option to open the quick menu with a hotkey (most probably because the sdk does not have a function for that yet), so again, simply holding the PS button to trigger the quick menu does not work.

On another note, a way to completely disable a button (power button in my case) would also be a sufficient workaround.

**Comment by Princess-of-Sleeping** [comment]
Currently, no such function is known. Or does not exist.
It may be found by reverse engineering SceShell stuff etc., but SceShell is 3MB and it is difficult to reverse engineer.

**Comment by Hanzyusuf** [comment]
excuse me for my ignorance, but isn't it possible to manually call the function (determined using call stack or stack trace) which gets called on physically holding the PS home button?

**Comment by Princess-of-Sleeping** [comment]
How
1. Call SceShell's DisplayQuickMenu function directly from user
2. Call ksceCtrlSetButtonEmulation from kernel

**Comment by Hanzyusuf** [comment]
I am guessing that the 2nd method won't work because it's the same thing as pressing the home button physically, the power button when pressed (due to being stuck at pressed) prevents the quick menu from opening somehow.

I am going to attempt the 1st method and see what I come up with. Thanks.

**Comment by Princess-of-Sleeping** [comment]
Edit2 > It's just a function to unlock what's locked. Doesn't open quick menu.
