### ISSUE TITLE
[Question] Setting up an arbitrary virtual address space

### ISSUE THREAD

**Issue by jvulcan** [vitasdk/vita-headers#690]
Hello,
With the current PS-Vita dev tools:
Is it possible to build a skprx module that can allocate memory for the running app, but with an arbitrary virtual address?
Like, when the app asks for memory, I'll give it starting from 0xA0000000 Virtual address onwards, using my own skprx module function.
If there is, which functions from the headers do I need to use?

I haven't found too much info about this specific topic, maybe you people could answer this,
Thanks in advance.

**Comment by Princess-of-Sleeping** [comment]
Call `ksceKernelAllocMemBlock` with Settings VA to `option.field_C` and `ATTR_VBASE` to `option.attr`

**Comment by Princess-of-Sleeping** [comment]
Also note that the kernel memory cannot be mapped to the user address because the process has its own address space.

```
Kern memory to User address `0x81010000`: Should failed
User memory to User address `0x81010000`: Should success
User memory to Kern address `0x01200000`: Should failed
Kern memory to Kern address `0x01200000`: Should success
```

**Comment by jvulcan** [comment]
Awesome, I'm investigating if I can mimic the available memory regions of the nintendo 3DS.
Because it doesn't expose dynamic addresses for heap, mappable memory, vram, mapped IO, etc.
`
#define OS_HEAP_AREA_BEGIN 0x08000000 ///< Start of the heap area in the virtual address space
#define OS_HEAP_AREA_END   0x0E000000 ///< End of the heap area in the virtual address space

#define OS_MAP_AREA_BEGIN  0x10000000 ///< Start of the mappable area in the virtual address space
#define OS_MAP_AREA_END    0x14000000 ///< End of the mappable area in the virtual address space

#define OS_OLD_FCRAM_VADDR 0x14000000 ///< Old pre-8.x linear FCRAM mapping virtual address
#define OS_OLD_FCRAM_PADDR 0x20000000 ///< Old pre-8.x linear FCRAM mapping physical address
#define OS_OLD_FCRAM_SIZE  0x8000000  ///< Old pre-8.x linear FCRAM mapping size (128 MiB)

#define OS_QTMRAM_VADDR    0x1E800000 ///< New3DS QTM memory virtual address
#define OS_QTMRAM_PADDR    0x1F000000 ///< New3DS QTM memory physical address
#define OS_QTMRAM_SIZE     0x400000   ///< New3DS QTM memory size (4 MiB; last 128 KiB reserved by kernel)

#define OS_MMIO_VADDR      0x1EC00000 ///< Memory mapped IO range virtual address
#define OS_MMIO_PADDR      0x10100000 ///< Memory mapped IO range physical address
#define OS_MMIO_SIZE       0x400000   ///< Memory mapped IO range size (4 MiB)

#define OS_VRAM_VADDR      0x1F000000 ///< VRAM virtual address
#define OS_VRAM_PADDR      0x18000000 ///< VRAM physical address
#define OS_VRAM_SIZE       0x600000   ///< VRAM size (6 MiB)

#define OS_DSPRAM_VADDR    0x1FF00000 ///< DSP memory virtual address
#define OS_DSPRAM_PADDR    0x1FF00000 ///< DSP memory physical address
#define OS_DSPRAM_SIZE     0x80000    ///< DSP memory size (512 KiB)

#define OS_KERNELCFG_VADDR 0x1FF80000 ///< Kernel configuration page virtual address
#define OS_SHAREDCFG_VADDR 0x1FF81000 ///< Shared system configuration page virtual address

#define OS_FCRAM_VADDR     0x30000000 ///< Linear FCRAM mapping virtual address
#define OS_FCRAM_PADDR     0x20000000 ///< Linear FCRAM mapping physical address
#define OS_FCRAM_SIZE      0x10000000 ///< Linear FCRAM mapping size (256 MiB)
`

**Comment by jvulcan** [comment]
Thank you, I will keep researching about this topic further.

**Comment by jvulcan** [comment]
> Call `ksceKernelAllocMemBlock` with Settings VA to `option.field_C` and `ATTR_VBASE` to `option.attr`
> 
> ```c
> #define ATTR_VBASE (1)
> ```

Hello, I can't find "Settings VA" to fill field_C.
my code:
`SceKernelAllocMemBlockKernelOpt opt;
	opt.size = sizeof(SceKernelAllocMemBlockKernelOpt);
	opt.field_C = 0x0; // ???? missing value
	opt.attr = romMH4U.textVAddr; // virtual address is 0x100000


	auto SceUID txtHndl = ksceKernelAllocMemBlock("3ds_text", 
		SCE_KERNEL_MEMBLOCK_TYPE_KERNEL_RX, // should be kernel right?
		romMH4U.textSz, opt);`

Checked everything with "settings" in the documentation and I found nothing.
And another thing, why does the Alloc function asks for a name?

Thanks in advance.

**Comment by Princess-of-Sleeping** [comment]
```C
SceKernelAllocMemBlockKernelOpt opt;
memset(&opt, 0, sizeof(opt));
opt.size = sizeof(opt);
opt.field_C = romMH4U.textVAddr;
opt.attr = ATTR_VBASE;
```

**Comment by jvulcan** [comment]
Thanks for the 'memset' note. I forgot to clear this thing in the first place; my c/c++ practical skill is a little rusted.
