### ISSUE TITLE
Incompatibilities with newlib

### ISSUE THREAD

**Issue by frangarcj** [vitasdk/vita-headers#73]
These symbols are imported by default 

https://github.com/vitasdk/vita-headers/blob/master/db.json#L1742-L1764

when using newlib you get

`/home/travis/vitasdk/bin/../lib/gcc/arm-vita-eabi/6.2.0/libgcc.a(_udivsi3.o): In function `__aeabi_uidiv':
(.text+0x0): multiple definition of `__aeabi_uidiv'
/home/travis/vitasdk/arm-vita-eabi/lib/libSceSysmem_stub.a(SceSysmem_SceSysclibForDriver___aeabi_uidiv.o):(.vitalink.fstubs+0x0): first defined here
collect2: error: ld returned 1 exit status`

If SceSysmem is removed from libspec it is partially fixed because if you use dynarec you need to import SceSysmem getting the same error.

I think the solution could be to split SceSysmen in SceSysmen, SceSysmemForDriver, SceSysmenForKernel

What do you think?

**Comment by xyzz** [comment]
```
15:04:08	<xyz[m]>	davee: https://github.com/vitasdk/vita-headers/issues/73 why do we even have `__aeabi_uidiv` in db.json? it comes from libgcc which should always be linked so we can remove these two
15:04:47	<frangarcj>	libgcc should be linked for modules?
15:06:06	<davee[m]>	don't ask me
15:06:06	<xyz[m]>	libgcc should always be linked
15:06:15	<xyz[m]>	unless there is a very very very good reason not to
15:06:43	<xyz[m]>	so even if you don't use standard libraries (crt0 and newlib) you still have to link libgcc, basically link it always if you are compiling with gcc
15:07:06	<frangarcj>	i thought libgcc was newlib
15:07:20	<davee[m]>	It's a yiffynoob commit
15:09:04	<-->>	Lupo511 (~Lupo511@host86-193-dynamic.18-79-r.retail.telecomitalia.it) has joined #vitasdk
15:10:19	<davee[m]>	does the lib clash with strcmp etc?
15:11:53	<frangarcj>	taihen is using -nostdlib
15:14:46	<xyz[m]>	nope, libgcc comes from gcc
15:15:09	<xyz[m]>	yes correct about taihen but doesn't it break homebrew?
15:15:12	<frangarcj>	yes
15:15:51	<frangarcj>	I think it should be better to break libraries in normal, forDriver, forKernel
15:15:52	<xyz[m]>	in the same way, homebrew using str* functions from newlib and being linked with SceSysmem
```

**Comment by yifanlu** [comment]
Is it possible to make the symbols weak?

**Comment by frangarcj** [comment]
Should we close this?
