### ISSUE TITLE
Change db JSON --> YAML?

### ISSUE THREAD

**Issue by devnoname120** [vitasdk/vita-headers#88]
Comparison:

JSON: https://gist.github.com/devnoname120/d5f71d70ae82414a051dc1ab698e8e9d
YAML: https://gist.github.com/devnoname120/ff2a08dbcfa0126d9099ce894f7fe783

The main advantages of YAML are its readability and native support for hexadecimal (which also means better syntax coloring).

Also, YAML supports commenting (with `#`) whereas JSON doesn't.

Related: #83

**Comment by enoposix** [comment]
I think we have consensus against this now.
