### ISSUE TITLE
please close.

### ISSUE THREAD

**Issue by bloodxia** [vitasdk/vita-headers#91]
cancel

**Comment by devnoname120** [comment]
Are you doing a User plugin or a Kernel plugin?

Once it works. please don't create a pull request to add your findings so that others can use these functions. Thank you for your help.

**Comment by d3m3vilurr** [comment]
@bloodxia you should share how get this header info.
i guess, it looks copied from gpl project...

**Comment by bloodxia** [comment]
@d3m3vilurr I use IDA. some method from Unity3D lib,some method and struct copy from PS3SDK.
but don't work.

**Comment by d3m3vilurr** [comment]
i cannot find struct & enum info from ps3sdk projects. can you share more info like url?

**Comment by bloodxia** [comment]
```cpp
/* $(SCE_PS3_ROOT)\target\ppu\lib\libsysutil_np_trophy_stub.a */

#include <np.h>

int GetTrophyCount()
{
	SceNpTrophyGameDetails game_details;
	sceNpTrophyGetGameInfo(1, 1, &game_details, NULL);
	return game_details.numTrophies;
}

void UnlockAllTrophys()
{
	for (int trophyId = 0; trophyId < GetTrophyCount(); trophyId++)
		sceNpTrophyUnlockTrophy(1, 1, trophyId, NULL);
}
```

RPCS3
https://github.com/RPCS3/rpcs3/blob/153a2d2b40be98d74c37833868b1906556b2c18d/rpcs3/Emu/Cell/Modules/sceNpTrophy.h

But I think can't used in psp2sdk.

**Comment by d3m3vilurr** [comment]
RPCS3 header cannot use in this project. it need license confirming :/ https://github.com/RPCS3/rpcs3/issues/2106

**Comment by bloodxia** [comment]
@d3m3vilurr It's not all from RPCS3.
I think RPCS3 header not work in PSV.
plugin has crash.struct not compatible.

**Comment by d3m3vilurr** [comment]
1. `not all from RPCS3` mean this file license must be `GPL`. we still can't use that before their confirming.
2. yes. I guess only can use some headers in `rpcs3/Emu/PSP2/Modules` without extra RE.

9 hours ago, updated RPCS3 issue, but we just mentioned `rpcs3/Emu/PSP2/Modules` directory
so if you still want to refer original file in `rpcs3/Emu/Cell/Modules` for the vitasdk project, please add comment to `RPCS3` issue.
